spring.datasource.url=jdbc:mysql://localhost:3306/sistema_taller
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email configuracion
email.username=salmargar8@gmail.com
email.password=voxk noye cokk ncxh

# Stripe configuracion
stripe.key.secret=sk_test_51RXuRERqjEEphIiB2TLfTcuxtaH654tyD8zbeJYEQDPB49Mcu2c3mQQNAUshzx0q86gALRCizSb7DxTCwLpUQlQk00C3Lo6PKQ
stripe.key.public=pk_test_51RXuRERqjEEphIiBCn0V2aDHTcG3el2DfNic2xjqDyDmKVgHpgYS5D3dJczNqYkNngeqlZcvQlJICCpEKSRibY1t000ljLBe8u



